Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,11 +18,33 @@ jobs:
       - name: Install dependencies
         run: npm install
 
+      # - name: ESLint
+      #   run: |
+      #     npm install eslint --save-dev
+      #     npm run fix .
+      #     npx eslint --max-warnings=40 "src/**/*.js" "."
+
       - name: ESLint
         run: |
           npm install eslint --save-dev
           npm run fix .
-          npx eslint --max-warnings=40 "src/**/*.js" "."
+      
+          # Get the total number of JavaScript files
+          total_files=$(find ./src -type f -name "*.js" | wc -l)
+      
+          # Run ESLint and calculate the percentage of warnings
+          eslint_result=$(npx eslint --format=json "src/**/*.js" ".")
+          total_warnings=$(echo $eslint_result | jq '.[0].warningCount')
+          percentage=$((total_warnings * 100 / total_files))
+      
+          # Set the threshold percentage
+          max_percentage=20
+      
+          # Check if the percentage exceeds the threshold
+          if [ "$percentage" -gt "$max_percentage" ]; then
+            echo "Exceeded the maximum allowed percentage of warnings. Failing the build."
+            exit 1
+          fi
 
       # - name: ESLint
       #   run: npm run fix .
